/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oracle;

import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author AstiviaMax
 */
public class EditEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form EditEmpleados
     */
    int id_Empleado;

    public int getId_Empleado() {
        return id_Empleado;
    }

    public void setId_Empleado(int id_Empleado) {
        this.id_Empleado = id_Empleado;
    }
    
    public EditEmpleados() {
        initComponents();
        Llenar_Combo();
        ComboEmpleados.setSelectedItem(null);
    }
    
    public void Llenar_Combo() {
        ComboEmpleados.removeAllItems(); //elimina los datos que pudieran existir previamente en el combo
        Empleados obj = new Empleados();
        ArrayList lista =obj.Combo_Empleados();
        Iterator iter = lista.iterator();
        while (iter.hasNext()) {
            Empleados emp = (Empleados) iter.next();
            ComboEmpleados.addItem(emp);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Borrar = new javax.swing.JButton();
        btn_Cancela = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_Guardar = new javax.swing.JButton();
        LastName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ComboEmpleados = new javax.swing.JComboBox<>();
        LastName2 = new javax.swing.JTextField();
        btn_Seleccionar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Salary = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Age = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        Phone = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_Borrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Borrar.setText("Eliminar Libro");
        btn_Borrar.setEnabled(false);
        btn_Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BorrarActionPerformed(evt);
            }
        });

        btn_Cancela.setText("Cancelar");
        btn_Cancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelaActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre:");

        Name.setEnabled(false);

        jLabel4.setText("Apellido Paterno:");

        btn_Guardar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Guardar.setText("Guardar Cambios");
        btn_Guardar.setEnabled(false);
        btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarActionPerformed(evt);
            }
        });

        LastName.setEnabled(false);

        jLabel1.setText("Seleccionar Empleado:");

        jLabel5.setText("Apellido Materno:");

        LastName2.setEnabled(false);

        btn_Seleccionar.setText("Cargar Datos");
        btn_Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SeleccionarActionPerformed(evt);
            }
        });

        jLabel6.setText("Salario:");

        Salary.setEnabled(false);

        jLabel9.setText("Edad:");

        Age.setEnabled(false);

        jLabel10.setText("Email:");

        Phone.setEnabled(false);

        Email.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Email.setEnabled(false);

        jLabel11.setText("Telefono:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(ComboEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Seleccionar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(Salary))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(LastName2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(Email))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Guardar)
                        .addGap(139, 139, 139)
                        .addComponent(btn_Borrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Cancela, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ComboEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Seleccionar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(LastName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Cancela)
                    .addComponent(btn_Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BorrarActionPerformed
        Empleados em = (Empleados) ComboEmpleados.getSelectedItem();
        this.setId_Empleado(em.getId());
        int r = em.Elimina_Empleado(this.getId_Empleado());
        if (r!=0) {
            JOptionPane.showMessageDialog(null, "Se Elimino el Empleado");
            Llenar_Combo();
            ComboEmpleados.setSelectedItem(null);
            Name.setEnabled(false);
            LastName.setEnabled(false);
            LastName2.setEnabled(false);
            Salary.setEnabled(false);
            Age.setEnabled(false);
            Email.setEnabled(false);
            Phone.setEnabled(false);
            this.setId_Empleado(0);
            btn_Guardar.setEnabled(false);
            btn_Borrar.setEnabled(false);
        }

    }//GEN-LAST:event_btn_BorrarActionPerformed

    private void btn_CancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelaActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btn_CancelaActionPerformed

    private void btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarActionPerformed
        if (Name.getText().equals("") || LastName.getText().equals("") || LastName2.getText().equals("")
             || Integer.parseInt(Age.getValue().toString()) <= 0 ||Email.getText().equals("")||Salary.getText().equals("")||Phone.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Favor de capturar los datos faltantes");
        } else {
            Empleados em = new Empleados();
            
            int r= em.Actualizar_Empleado( Name.getText(), LastName.getText(), LastName2.getText(), Integer.parseInt(Age.getValue().toString()), 
                    Email.getText(), Double.parseDouble(Phone.getText()),Double.parseDouble(Salary.getText()),this.getId_Empleado());
            if (r != 0) {
                Name.setText("");LastName.setText("");LastName2.setText("");Email.setText("");Salary.setText("");Age.setValue(0);Phone.setText("");
                ComboEmpleados.setSelectedItem(null);
                JOptionPane.showMessageDialog(null, "Datos Modificados correctamente");
            } else {
                JOptionPane.showMessageDialog(null, "Ocurrio un error");
            }
        }
    }//GEN-LAST:event_btn_GuardarActionPerformed

    private void btn_SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SeleccionarActionPerformed
        Empleados empleado = (Empleados) ComboEmpleados.getSelectedItem();
        if (empleado ==null) {
            JOptionPane.showMessageDialog(null,"Seleccione un Empleado");
        }else{
            Name.setText(empleado.getNombre()); Name.setEnabled(true);
            LastName.setText(empleado.getAp_pat());LastName.setEnabled(true);
            LastName2.setText(empleado.getAp_mat());LastName2.setEnabled(true);
            Salary.setText(String.valueOf(empleado.getSalario()));Salary.setEnabled(true);
            Age.setValue(empleado.getEdad());Age.setEnabled(true);
            Email.setText(empleado.getEmail());Email.setEnabled(true);
            Phone.setText(String.valueOf(empleado.getNumero()));Phone.setEnabled(true);
            this.setId_Empleado(empleado.getId());
            btn_Guardar.setEnabled(true);btn_Borrar.setEnabled(true);
        }

    }//GEN-LAST:event_btn_SeleccionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Age;
    private javax.swing.JComboBox<Empleados> ComboEmpleados;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField LastName;
    private javax.swing.JTextField LastName2;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Phone;
    private javax.swing.JTextField Salary;
    private javax.swing.JButton btn_Borrar;
    private javax.swing.JButton btn_Cancela;
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JButton btn_Seleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
